# Generated by Django 4.2 on 2024-04-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('cancel', 'отмена публикации'), ('change description', 'изменить описание'), ('change category', 'изменить категорию')), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
