# Generated by Django 4.2 on 2024-03-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'продавец', 'verbose_name_plural': 'продавцы'},
        ),
    ]
