# Generated by Django 4.0.4 on 2024-03-03 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='категория')),
                ('category_description', models.CharField(max_length=200, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='название')),
                ('product_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='изображение')),
                ('product_price', models.IntegerField(blank=True, null=True, verbose_name='цена')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='дата записи')),
                ('updated_at', models.DateField(auto_now_add=True, null=True, verbose_name='последние изменения')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.categories', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
