# Generated by Django 4.0.4 on 2024-03-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='manufactured_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата производства'),
        ),
    ]
