# Generated by Django 4.0.4 on 2024-03-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='описание'),
        ),
    ]
