# Generated by Django 4.2 on 2024-04-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_products_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'permissions': (('cancel', 'отмена публикации'), ('change description', 'изменить описание'), ('change category', 'изменить категорию')), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
