# Generated by Django 4.2 on 2024-04-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='publication_sign',
            field=models.BooleanField(default=True, verbose_name='публикация'),
        ),
    ]
