# Generated by Django 4.2 on 2024-04-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_products_publication_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='number_of_views',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
