# Generated by Django 4.2 on 2024-04-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_products_number_of_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'permissions': (('cancel', 'отмена публикации'), ('change_description', 'изменить описание'), ('change_category', 'изменить категорию')), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
